### ISSUE TITLE
suggestion: add a (template/optional) LICENSE file to a generated plugin

### ISSUE THREAD

**Issue by andypiper** [laurent22/generator-joplin#6]
I noticed that a plugin that I want to contribute to, does not have a LICENSE file - so I opened an issue requesting that the status of the code be clarified.

It might be a good idea to add the creation of the LICENSE file to the template so that the author is prompted to add something. An alternative option would be to add a hint to the README file to suggest that the author clarifies license and contribution guidelines when they release or announce a new plugin.

**Comment by laurent22** [comment]
Hello, this repository is no longer active. The code for the generator is now on https://github.com/laurent22/joplin/

**Comment by andypiper** [comment]
https://discourse.joplinapp.org/t/suggestion-add-a-template-license-to-generated-plugins/30993
